"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# คือ configuration หลัก และตรงนี้เป็นไฟล์ที่เราต้องจัดการเรื่อง security ทันที

from pathlib import Path

# โหลดค่าจากไฟล์ .env เข้า environment variables
# ทำให้ข้อมูลสำคัญ เช่น SECRET_KEY และ database credentials
# ไม่ต้องเขียนค่าจริงลงใน source code

import os
from dotenv import load_dotenv


# BASE_DIR คือ path หลักของ Django project
# ใช้เป็นจุดอ้างอิงสำหรับไฟล์ต่าง ๆ เช่น .env, templates และ static files
BASE_DIR = Path(__file__).resolve().parent.parent


# โหลดค่าจากไฟล์ .env เข้า environment variables
# ทำให้ข้อมูลสำคัญ เช่น SECRET_KEY และ database credentials
# ไม่ต้องเขียนค่าจริงลงใน source code
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY ใช้สำหรับฟังก์ชันด้าน cryptographic signing ของ Django
# ค่าจริงต้องอยู่ใน .env เท่านั้น และห้าม commit ลง Git
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# DEBUG ใช้เปิดข้อมูลช่วย debug ระหว่าง development
# อ่านค่าจาก .env เพื่อไม่ผูก environment setting ไว้กับ source code
# ถ้าไม่มี DJANGO_DEBUG จะใช้ False เป็นค่าเริ่มต้นเพื่อความปลอดภัย
DEBUG = os.environ.get("DJANGO_DEBUG", "False").strip().lower() == "true"

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Django เชื่อมต่อ PostgreSQL โดยอ่านค่าจาก .env
# เพื่อไม่ให้ชื่อผู้ใช้ รหัสผ่าน หรือข้อมูลการเชื่อมต่อจริง
# ถูก hard-code ลงใน source code หรือถูก commit ขึ้น Git
DATABASES = {
    "default": {
        # ระบุให้ Django ใช้ PostgreSQL backend
        "ENGINE": "django.db.backends.postgresql",

        # ชื่อ database ที่ Django application จะใช้งาน
        "NAME": os.environ["POSTGRES_DB"],

        # PostgreSQL user/role สำหรับ application นี้โดยเฉพาะ
        "USER": os.environ["POSTGRES_USER"],

        # Password อยู่ใน .env เท่านั้น
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],

        # Development ใช้ PostgreSQL Server ในเครื่อง
        # ถ้าไม่ได้กำหนดค่าไว้ จะใช้ localhost เป็นค่าเริ่มต้น
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),

        # Port มาตรฐานของ PostgreSQL คือ 5432
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
