# Generated by Django 6.0.8 on 2026-08-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
